### ISSUE TITLE
README clarification on RNGDet++

### ISSUE THREAD

**Issue by Weixing-Zhang** [TonyXuQAQ/Topo-boundary#23]
I saw the following in the README "You could try our latest proposed work [RNGDet++](https://github.com/TonyXuQAQ/RNGDetPlusPlus), which is much more powerful and flexible than iCurb." I thought RNGDet++ is a road network extraction method and iCurb is more of a road boundary detection method. I am curious how these two can be comparable. Any helps are much appreciated. 

https://raw.githubusercontent.com/TonyXuQAQ/Topo-boundary/master/README.md#:~:text=%23%23%20New%20models%0AYou%20could%20try%20our%20latest%20proposed%20work%20%5BRNGDet%2B%2B%5D(https%3A//github.com/TonyXuQAQ/RNGDetPlusPlus)%2C%20which%20is%20much%20more%20powerful%20and%20flexible%20than%20iCurb.

**Comment by TonyXuQAQ** [comment]
Thanks for the question. iCurb can only direct road elements without intersections (i.e., only road elements that are simple polylines). RNGDet++ can handle road elements with more complicated topology (e.g., split, merge and intersection). We did not directly compare them, since they are for different applications. RNGDet++ should be more applicable for real-world applications.

**Comment by Weixing-Zhang** [comment]
Thank you so much for your quick response. One follow-up is that does RNGDet++ generate road boundaries?

**Comment by TonyXuQAQ** [comment]
Sure. Theoretically, RNGDet++ can handle road elements with arbitrary topology. Detecting curbs by RNGDet++ is overkill. But we did not do corresponding experiments. You may try it by yourself.

**Comment by Weixing-Zhang** [comment]
Got it. Thank you for the confirmation.
