### ISSUE TITLE
Can not download the dataset

### ISSUE THREAD

**Issue by xmqv0913** [TonyXuQAQ/Topo-boundary#7]
When I downloaded "cropped_tiff.zip", Google always display :

> Sorry, you can't view or download this file at this time.
> Too many users have viewed or downloaded this file recently. Please try accessing the file again later...

could you please give me a private share so that I can download this data

**Comment by TonyXuQAQ** [comment]
Thanks for the question. 

This bug is caused by the limitation of file transfer bandwidth of Google drive. When a large file is accessed beyond a number of times, Google drive bans all users and says "download quota runs out". This ban should be canceled 24 hours later, but we cannot do anything to solve it immediately.

To fix this, we provide a new script for tiff image download ```./dataset/get_data_new.bash```. Please check this [link](https://github.com/TonyXuQAQ/Topo-boundary/tree/master/dataset#new-dataset-download-method-not-fully-verified). In this script, we directly download the raw data from NYC database and do a set of processing to obtain aerial images that we need. It may take some time for data download and processing. We did some simple tests, and this script should work properly. We will fully verify the manuscript soon.

Other data (e.g., checkpoints, labels) should be able to be downloaded from Google drive correctly. If not, please notify us. Thank you so much.

**Comment by xmqv0913** [comment]
Thanks for your reply, I will try this way.

There may be a little problem except 2018_Manhattan_Orthoimagery_jp2.zi in "
./dataset/get_data_new.bash", for example:
" wget 2018_Kings_Orthoimagery_jp2.zip
https://data.cityofnewyork.us/download/q937-un2p/application%2Fzip"
should be corrected to:
" wget -O 2018_Kings_Orthoimagery_jp2.zip
https://data.cityofnewyork.us/download/q937-un2p/application%2Fzip"

Zhenhua Xu ***@***.***> 于2021年8月13日周五 上午12:47写道：

**Comment by TonyXuQAQ** [comment]
Thanks for reporting the typo. It has been fixed.

**Comment by xmqv0913** [comment]
Hi
    I have downloaded the data following "get_data_new.bash" , and generated “cropped_tiff”. But compared to the files in data_split.json, the  generated “cropped_tiff” seems to be missing a small part, so the existence check needs to be added to the dataloader.

**Comment by TonyXuQAQ** [comment]
Sorry for the late reply. The bug you mentioned has been fixed. In the previous bash script, we download the 2018 version of NYC Aerial Image, which does not contain all the images in the 2016 version of NYC Aerial Image. We have updated the download link, and the bash script should work fine now.
