### ISSUE TITLE
About the initial Vertex Q in ICurb

### ISSUE THREAD

**Issue by wulongjian** [TonyXuQAQ/Topo-boundary#8]
hello, as your mentioned in ICurb paper:
        **_During training, the initial vertex candidates Q are obtained by adding Gaussian noises to the ground-truth initial vertices, while during testing, Q is generated from the segmentation results S and H by the proposed algorithm._**
but in your code, Whether it’s training or testing, the way to obtain the initial Vertex Q seems to be done directly from the data load, and it has nothing to do with the S and H branch. Did I understand it wrong? Below is the relevant code.
iCurb/main_val.py
```
    # =================working on an image=====================
    for i, data in enumerate(network.dataloader_valid):
        _, _, tiff, mask, name, init_points, end_points = data
        name = name[0][-14:-5]
        tiff = tiff.to(args.device)
        mask, init_points, end_points = mask[0], init_points[0], end_points[0]
```
Looking forward to your reply, thanks a lot.

**Comment by TonyXuQAQ** [comment]
Thanks for the question. In this benchmark dataset, for a fair comparison, the initial vertices are just GT values, which is mentioned in the readme file of graph-based methods. 
![image](https://user-images.githubusercontent.com/33851435/129675503-6ca8e53e-b00f-4f55-8463-98fa8109ea7c.png)


Because different graph-based methods have different ways to find initial vertices (e.g., RoadTracer directly uses GT values, while VecRoad and iCurb uses predicted values), and the accuracy of the initial vertices will affect the inference performance of afterward iterative graph growing. Therefore, for simplicity and fair comparison, at this stage, we only use GT initial vertices.

**Comment by wulongjian** [comment]
Thank you for your answer， I'm sorry I didn't read the Readme file carefully. I just studied this part recently and not very familiar with the code.  Can you provide the code that can generate the initial point coordinates instead of directly using the GT value? My email is **_wulongjian@stu.ouc.edu.cn_**  Looking forward to your reply, thanks a lot.

**Comment by wulongjian** [comment]
Ok. Looking forworing to your future releases
